#!/usr/bin/env python3
"""
Export one vessel chip (same RGB as review cards, without overlays) with several
sharpening / mild-enhancement variants for visual comparison.

Industry-oriented notes (low-res EO, display-sized chips):
- Prefer sharpening **luminance** (Y in YCrCb or L in Lab) to limit chroma halos.
- Unsharp mask (USM) does not recover true resolution; it trades softness (resampling)
  for edge emphasis — keep radius small (often ~0.7–2 px) and strength modest.
- CLAHE on luminance can lift local contrast without global color shifts if chroma is
  left untouched.

Examples:
  python scripts/generate_chip_sharpen_samples.py --png path/to/chip.png -o artifacts/chip_sharpen_samples
  python scripts/generate_chip_sharpen_samples.py --jsonl labels.jsonl --id <uuid> -o artifacts/chip_sharpen_samples
"""

from __future__ import annotations

import argparse
import io
import json
import sys
from pathlib import Path
from typing import Callable

import cv2
import numpy as np
from PIL import Image, ImageFilter

# Project root (parent of scripts/)
_ROOT = Path(__file__).resolve().parents[1]
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))


def _readme_text() -> str:
    return """Chip sharpening sample pack
==============================

Generated by scripts/generate_chip_sharpen_samples.py

Files (original + 9 variants):
- 00_original.png — resized RGB chip only (no scale / north / text).
- 01_pil_unsharp_mild / 02_pil_unsharp_medium — PIL UnsharpMask on full RGB (quick, can add slight chroma halos).
- 03_ycbcr_usm — Gaussian USM on Y only, YCrCb merge.
- 04_lab_l_usm — Gaussian USM on L only (OpenCV Lab).
- 05_lab_l_clahe — CLAHE on L only (local contrast).
- 06_lab_l_clahe_usm — CLAHE on L then mild USM on L.
- 07_cv2_detail_enhance — OpenCV detailEnhance (edge-aware, generally color-stable).
- 08_edge_preserving_lab_usm — edgePreservingFilter then mild L-channel USM.
- 09_bilateral_lab_usm — bilateral filter then mild L-channel USM.

Practice (low-res EO): favor luminance-only USM or CLAHE-on-L; avoid heavy full-RGB sharpening.
"""


def _rgb_to_arr(im: Image.Image) -> np.ndarray:
    return np.asarray(im.convert("RGB"), dtype=np.uint8)


def _arr_to_pil(rgb: np.ndarray) -> Image.Image:
    return Image.fromarray(np.clip(rgb, 0, 255).astype(np.uint8), mode="RGB")


def _gaussian_usm_y_channel(
    rgb: np.ndarray, *, sigma: float, amount: float, code_in: int, code_out: int
) -> np.ndarray:
    """USM on first channel of a 3-channel colorspace (e.g. YCrCb or Lab)."""
    c = cv2.cvtColor(rgb, code_in)
    c0, c1, c2 = cv2.split(c)
    blur = cv2.GaussianBlur(c0, (0, 0), sigma)
    y2 = cv2.addWeighted(c0, 1.0 + amount, blur, -amount, 0)
    y2 = np.clip(y2, 0, 255).astype(np.uint8)
    merged = cv2.merge([y2, c1, c2])
    return cv2.cvtColor(merged, code_out)


def _lab_l_clahe(rgb: np.ndarray, *, clip: float, tile: int) -> np.ndarray:
    lab = cv2.cvtColor(rgb, cv2.COLOR_RGB2LAB)
    l, a, b = cv2.split(lab)
    clahe = cv2.createCLAHE(clipLimit=clip, tileGridSize=(tile, tile))
    l2 = clahe.apply(l)
    return cv2.cvtColor(cv2.merge([l2, a, b]), cv2.COLOR_LAB2RGB)


def method_01_pil_unsharp_mild(rgb: np.ndarray) -> np.ndarray:
    im = _arr_to_pil(rgb).filter(ImageFilter.UnsharpMask(radius=1, percent=110, threshold=4))
    return _rgb_to_arr(im)


def method_02_pil_unsharp_medium(rgb: np.ndarray) -> np.ndarray:
    im = _arr_to_pil(rgb).filter(ImageFilter.UnsharpMask(radius=1.2, percent=150, threshold=2))
    return _rgb_to_arr(im)


def method_03_ycbcr_usm(rgb: np.ndarray) -> np.ndarray:
    return _gaussian_usm_y_channel(
        rgb, sigma=1.0, amount=0.55, code_in=cv2.COLOR_RGB2YCrCb, code_out=cv2.COLOR_YCrCb2RGB
    )


def method_04_lab_l_usm(rgb: np.ndarray) -> np.ndarray:
    return _gaussian_usm_y_channel(
        rgb, sigma=1.0, amount=0.5, code_in=cv2.COLOR_RGB2LAB, code_out=cv2.COLOR_LAB2RGB
    )


def method_05_lab_l_clahe(rgb: np.ndarray) -> np.ndarray:
    return _lab_l_clahe(rgb, clip=2.0, tile=8)


def method_06_lab_l_clahe_usm(rgb: np.ndarray) -> np.ndarray:
    mid = _lab_l_clahe(rgb, clip=2.0, tile=8)
    return _gaussian_usm_y_channel(
        mid, sigma=0.8, amount=0.35, code_in=cv2.COLOR_RGB2LAB, code_out=cv2.COLOR_LAB2RGB
    )


def method_07_detail_enhance(rgb: np.ndarray) -> np.ndarray:
    bgr = cv2.cvtColor(rgb, cv2.COLOR_RGB2BGR)
    out = cv2.detailEnhance(bgr, sigma_s=12, sigma_r=0.12)
    return cv2.cvtColor(out, cv2.COLOR_BGR2RGB)


def method_08_edge_preserving_lab_usm(rgb: np.ndarray) -> np.ndarray:
    bgr = cv2.cvtColor(rgb, cv2.COLOR_RGB2BGR)
    smooth = cv2.edgePreservingFilter(bgr, flags=cv2.RECURS_FILTER, sigma_s=50, sigma_r=0.4)
    mid = cv2.cvtColor(smooth, cv2.COLOR_BGR2RGB)
    return _gaussian_usm_y_channel(
        mid, sigma=1.0, amount=0.45, code_in=cv2.COLOR_RGB2LAB, code_out=cv2.COLOR_LAB2RGB
    )


def method_09_bilateral_lab_usm(rgb: np.ndarray) -> np.ndarray:
    bgr = cv2.cvtColor(rgb, cv2.COLOR_RGB2BGR)
    blur = cv2.bilateralFilter(bgr, d=5, sigmaColor=40, sigmaSpace=40)
    mid = cv2.cvtColor(blur, cv2.COLOR_BGR2RGB)
    return _gaussian_usm_y_channel(
        mid, sigma=1.0, amount=0.5, code_in=cv2.COLOR_RGB2LAB, code_out=cv2.COLOR_LAB2RGB
    )


METHODS: list[tuple[str, Callable[[np.ndarray], np.ndarray]]] = [
    ("01_pil_unsharp_mild", method_01_pil_unsharp_mild),
    ("02_pil_unsharp_medium", method_02_pil_unsharp_medium),
    ("03_ycbcr_usm", method_03_ycbcr_usm),
    ("04_lab_l_usm", method_04_lab_l_usm),
    ("05_lab_l_clahe", method_05_lab_l_clahe),
    ("06_lab_l_clahe_usm", method_06_lab_l_clahe_usm),
    ("07_cv2_detail_enhance", method_07_detail_enhance),
    ("08_edge_preserving_lab_usm", method_08_edge_preserving_lab_usm),
    ("09_bilateral_lab_usm", method_09_bilateral_lab_usm),
]


def _load_chip_from_jsonl(jsonl_path: Path, record_id: str, project_root: Path) -> Image.Image:
    from aquaforge.review_card_export import build_review_card_png

    raw = record_id.strip()
    rec = None
    with jsonl_path.open(encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                obj = json.loads(line)
            except json.JSONDecodeError:
                continue
            rid = str(obj.get("id", ""))
            if rid == raw:
                rec = obj
                break
    if rec is None:
        raise SystemExit(f"Record id not found in {jsonl_path}: {raw!r}")

    png_bytes, meta = build_review_card_png(
        rec, project_root=project_root, chip_image_only=True
    )
    if png_bytes is None:
        raise SystemExit("build_review_card_png(chip_image_only=True) failed for this record.")
    im = Image.open(io.BytesIO(png_bytes))
    im.load()
    return im.convert("RGB")


def main() -> None:
    ap = argparse.ArgumentParser(description="Write chip sharpening comparison PNGs.")
    ap.add_argument(
        "-o",
        "--out-dir",
        type=Path,
        default=_ROOT / "artifacts" / "chip_sharpen_samples",
        help="Output directory (created if missing).",
    )
    ap.add_argument("--png", type=Path, help="Input RGB chip PNG (any size).")
    ap.add_argument("--jsonl", type=Path, help="JSONL review export (use with --id).")
    ap.add_argument("--id", dest="record_id", help="Record id to match in JSONL.")
    ap.add_argument(
        "--project-root",
        type=Path,
        default=_ROOT,
        help="Project root for resolving tci_path (JSONL mode).",
    )
    args = ap.parse_args()

    if bool(args.png) == bool(args.jsonl):
        ap.error("Specify exactly one of --png or --jsonl")

    if args.jsonl:
        if not args.record_id:
            ap.error("--jsonl requires --id")
        pil_in = _load_chip_from_jsonl(args.jsonl, args.record_id, args.project_root)
    else:
        assert args.png is not None
        if not args.png.is_file():
            raise SystemExit(f"Missing file: {args.png}")
        pil_in = Image.open(args.png).convert("RGB")

    out_dir = args.out_dir.resolve()
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "README.txt").write_text(_readme_text(), encoding="utf-8")

    rgb0 = _rgb_to_arr(pil_in)
    _arr_to_pil(rgb0).save(out_dir / "00_original.png", optimize=True)

    for name, fn in METHODS:
        out = fn(rgb0.copy())
        _arr_to_pil(out).save(out_dir / f"{name}.png", optimize=True)
        print("wrote", out_dir / f"{name}.png")

    print("done:", out_dir)


if __name__ == "__main__":
    main()
